apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCEIov+g/Zgr/i1ohurhWhY+7QCLIhWmGQgxsjQWAoHemirUg9sYig/H9PMp8h/Rz3ui0cVRKlNXUDbtIqsco+lQPU70I8f05HLYKOh8eFCXoMBbzy3CjTmvlxnCyzEYtZWGHGnQWW8p5Py6qa4VSsN0i9OLmDrEWMvdnpgPNXkbIKBAkxbXQKvM8x7S1zI45cmLJQm6iPzvifemRlEyDg24Z5Az44ygJmWWj449vtTiFyW+0eUXGKEOm/1xHaNQkVyp4cEFZcbExIc29tYEKwvsKLzmtUa54PjJLjIGFSIkBKGHNUR4WbyRVR2KXA/0MhAo4bIJau1JreUIiQh3xIhO45GHYtN8WlWjLzJ3h6BGw1eT2hneqN/WChZcDp7xNr+GdNGSOmzGzF/VKAqh8ktbxwS9aKS9kmwrzeOzGO0rSXz5e5+sY8u+/eyTN+uSGpp4xz/FCqLvFToTl3qloAT0MULV2a9BhOnCHJ6PeEQ4UsrYki1fKOlxmTgf62fry+YzQChTRcy1KVe0Tzhv2LOiwm0Clrq/JLxlOt00Qfp8gm3FjTPK425vHJkNH3uQqMlhYQQy/EuaOF4rcdixYzhn+y/spdEgmjvG1o7aCXtiEP3EVtGGLBPKumLQ5fk0wSON9fkitH4xWEpxMIJs6QApN+W1pXPQByucD29pVyAmoq6H7NIa2NIkrME4fLDz4Mi9jYliG1dQxmjvlj2GHZRdZ5JGF/CA40k2A5sUj0GgYa8U2ShKel6
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

